# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d65df10030b4ad7a85a33f8aab1728739f29df384ec06cd9adb3b7cb308134333965c75c80202e05d08884798130f30f72e0304f8004c2bed0ae4613334dc0

test:
  secret_key_base: 3b5eb807df08759c17078b797b13c9486322dd590679d66f6f54dddd008207eace1045d46ab3d6e90a60710c63737c7b2dd38f2e6e3955a388c43b22673b8f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
